# Generated by Django 3.2.2 on 2023-09-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(max_length=11)),
                ('partNumber', models.CharField(max_length=30)),
                ('productName', models.CharField(max_length=400)),
                ('part1', models.CharField(max_length=30)),
                ('part2', models.CharField(max_length=30)),
                ('part3', models.CharField(max_length=30)),
                ('part4', models.CharField(max_length=30)),
                ('part5', models.CharField(max_length=30)),
                ('part6', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'BOM',
                'managed': False,
            },
        ),
    ]
