# Generated by Django 3.2.2 on 2023-10-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_importinspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyCompleted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('partNumber', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('lotNo', models.CharField(max_length=30)),
                ('completed_date', models.DateTimeField()),
                ('instructed_quantity', models.IntegerField()),
                ('remains', models.IntegerField()),
                ('product_no', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=100)),
                ('receive_check', models.CharField(max_length=10)),
                ('total_instructed', models.IntegerField()),
            ],
            options={
                'db_table': 'assemblyCompleted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssemblyInstruction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('partNumber', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('lotNo', models.CharField(max_length=30)),
                ('instruction_date', models.DateTimeField()),
                ('instructed_quantity', models.IntegerField()),
                ('remains', models.IntegerField()),
                ('product_no', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=100)),
                ('total_instructed', models.IntegerField()),
            ],
            options={
                'db_table': 'assemblyInstruction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('warehouse', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'external_member',
                'managed': False,
            },
        ),
    ]
