# Generated by Django 3.2.2 on 2023-10-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assemblycompleted_assemblyinstruction_externalmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMemberToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='api.externalmember', verbose_name='External Member')),
            ],
            options={
                'unique_together': {('user', 'key')},
            },
        ),
    ]
