# Generated by Django 3.2.2 on 2023-10-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_externalmembertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmembertoken',
            name='expires_at',
            field=models.DateTimeField(null=True, verbose_name='Expires At'),
        ),
    ]
