# Generated by Django 3.2.2 on 2023-11-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_externalmembertoken_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('partNumber', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('lotNo', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('inputDateTime', models.DateTimeField()),
                ('user_id', models.CharField(max_length=100)),
                ('date_of_receipt', models.DateField()),
            ],
            options={
                'db_table': 'external_inventory',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='bom',
            table='BOM_web',
        ),
    ]
