# Generated by Django 3.2.2 on 2024-01-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_externalmembertoken_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('partNumber', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('lotNo', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('inputDateTime', models.DateTimeField()),
                ('user_id', models.CharField(max_length=100)),
                ('date_of_receipt', models.DateField()),
            ],
            options={
                'db_table': 'external_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_num', models.CharField(max_length=100)),
                ('before_state', models.CharField(max_length=100)),
                ('after_state', models.CharField(max_length=100)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sub_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwintechWarehousing',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('partNumber', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('lotNo', models.CharField(max_length=30)),
                ('warehousingDate', models.DateTimeField()),
                ('warehousingWorker', models.CharField(max_length=30)),
                ('improvedItem', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=100)),
                ('lastState', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'warehousing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('log', models.CharField(max_length=100)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'web_logs',
                'managed': False,
            },
        ),
    ]
