# Generated by Django 3.2.2 on 2024-08-26 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_externalinventory_sublog_swintechwarehousing_weblogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalmember',
            options={},
        ),
        migrations.AlterField(
            model_name='externalmembertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_auth_token', to=settings.AUTH_USER_MODEL, verbose_name='External Member'),
        ),
    ]
