# Generated by Django 3.2.2 on 2024-08-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240826_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalmember',
            options={'managed': False},
        ),
    ]
