# Generated by Django 3.2.2 on 2024-08-26 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_externalmember_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalmembertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='api.externalmember', verbose_name='External Member'),
        ),
    ]
